<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools = [
            [
                'id' => 1,
                'name' => 'SMA Negeri 1 Kesamben',
                'short_name' => 'SMANSA',
                'address' => 'Jl. Bromo, Kesamben, Kec. Kesamben, Kabupaten Blitar, Jawa Timur 66191',
                'phone' => '0342-331397',
                'email' => 'info@sman1kesamben.sch.id',
                'website' => 'https://sman1kesamben.sch.id/',
                'logo' => 'school/logo/2Z9OToLjFcWfFbxfFPA8Mw465VRZ6nHpEMYyF8kF.png',
                'status' => 'active',
                'created_at' => '2025-09-09 01:09:23',
                'updated_at' => '2025-09-09 06:27:20',
            ],
            [
                'id' => 2,
                'name' => 'SMA Negeri 10 Malang',
                'short_name' => 'SMANDASA',
                'address' => 'Jl. Danau Grati No.1, Sawojajar, Kec. Kedungkandang, Kota Malang, Jawa Timur 65139',
                'phone' => '(0341) 719300',
                'email' => 'sman10malang@yahoo.com',
                'website' => 'https://smanegeri10malang.sch.id/',
                'logo' => 'school/logo/1U3RxBj7AJvyyBOgIXFNO5vrbGz1NiESxIkw5aFZ.png',
                'status' => 'active',
                'created_at' => '2025-09-09 01:09:23',
                'updated_at' => '2025-09-09 06:28:39',
            ],
            [
                'id' => 3,
                'name' => 'SMA Negeri 1 Bangil',
                'short_name' => 'SMANBA',
                'address' => 'Jalan Bader No. 3, Kalirejo, Bangil, Kabupaten Pasuruan, Jawa Timur 67153',
                'phone' => '747219',
                'email' => 'smanegeri1bangil@gmail.com',
                'website' => 'http://www.sman1bangil.sch.id',
                'logo' => 'school/logo/yCQWm7qQyxKvRkYrFZVhwuPSmPfDKQiDzsWxLG5n.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:02:55',
                'updated_at' => '2025-09-09 06:30:18',
            ],
            [
                'id' => 4,
                'name' => 'SMA Negeri 1 Sangatta Utara',
                'short_name' => 'SMANSATARA',
                'address' => 'Jalan A. Wahab Syahranie, Teluk Lingga, Kecamatan Sangatta Utara, Kutai Timur',
                'phone' => '0549-22572',
                'email' => 'info@smansatara.sch.id',
                'website' => 'https://www.smansatara.sch.id/',
                'logo' => 'school/logo/XfqHnvIslaH5LVjXfNoFfFdXJK4ziDzwfAbYaget.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:33:26',
                'updated_at' => '2025-09-09 06:33:26',
            ],
            [
                'id' => 5,
                'name' => 'SMA Negeri 2 Malang',
                'short_name' => 'SMANDA',
                'address' => 'Jl. Laks. Martadinata No. 84, Sukoharjo, Klojen, Malang, Jawa Timur',
                'phone' => '(0341) 366311',
                'email' => 'humas@sman2-malang.sch.id',
                'website' => 'www.sman2-malang.sch.id',
                'logo' => 'school/logo/slKMCL0iK1V40ePPgtBTOFY6KWHzxibX69CUXimW.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:35:49',
                'updated_at' => '2025-09-09 06:35:49',
            ],
            [
                'id' => 6,
                'name' => 'SMA Negeri 7 Malang',
                'short_name' => 'SHABANTASA',
                'address' => 'Jl. Cengger Ayam I No.14, Tulusrejo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141',
                'phone' => '085 231 787 787',
                'email' => 'sekolah@sman7malang.sch.id',
                'website' => 'https://sman7malang.sch.id/',
                'logo' => 'school/logo/oghASQ8eroz0C4RwrjTlIJTNbNZyciiftOFJkHQs.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:36:48',
                'updated_at' => '2025-09-09 06:36:48',
            ],
            [
                'id' => 7,
                'name' => 'SMA Negeri 1 Tumpang',
                'short_name' => 'SMANETA',
                'address' => 'Jl. Kamboja No. 10, Malangsuo, Tumpang, Kabupaten Malang, Jawa Timur',
                'phone' => '0341-788165',
                'email' => 'sman1tumpang@gmail.com',
                'website' => 'https://www.sman1tumpang.sch.id/',
                'logo' => 'school/logo/dqqjd8tRbmBNpjNJd99svopYDPh2v7gY5L5sEwS5.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:38:34',
                'updated_at' => '2025-09-09 06:40:52',
            ],
            [
                'id' => 8,
                'name' => 'SMA Negeri 1 Kepanjen',
                'short_name' => 'SMANEKA',
                'address' => 'Jalan A. Yani No. 48, Kepanjen, Kabupaten Malang, Jawa Timur',
                'phone' => '341394262',
                'email' => 'smanekamlg@yahoo.com',
                'website' => 'http://www.sman1kepanjen.sch.id',
                'logo' => 'school/logo/xBiu9f8q5DN7r4cHLHUlA0OsVpZDpvWSsNTMoouh.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:42:04',
                'updated_at' => '2025-09-09 06:42:04',
            ],
            [
                'id' => 9,
                'name' => 'SMA Negeri 4 Malang',
                'short_name' => 'STETSA',
                'address' => 'Jl. Tugu No.1, Klojen, Kec. Klojen, Kota Malang, Jawa Timur 65111',
                'phone' => '0341 325267',
                'email' => 'info@sman4malang.sch.id',
                'website' => 'https://sman4malang.sch.id/',
                'logo' => 'school/logo/cHMLTLB9temie50vCxQxzAWCnTHl5odsTuGYSsQJ.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:42:57',
                'updated_at' => '2025-09-09 06:42:57',
            ],
            [
                'id' => 10,
                'name' => 'SMA Negeri 5 Malang',
                'short_name' => 'DHAMYSOGA',
                'address' => 'Jl. Tanimbar No.24, Kasin, Kec. Klojen, Kota Malang, Jawa Timur 65117',
                'phone' => '081 297 000 956',
                'email' => 'inbox@sman5malang.sch.id',
                'website' => 'https://sman5malang.sch.id',
                'logo' => 'school/logo/bGUcAfziTuAYgvY6RV0On7rOJ6SPk6QLvjJFCS1v.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:43:47',
                'updated_at' => '2025-09-09 06:43:47',
            ],
            [
                'id' => 11,
                'name' => 'SMA Negeri 9 Malang',
                'short_name' => 'SMANAWA',
                'address' => 'Jl. Puncak Borobudur No. 1, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65142',
                'phone' => '(0341) 471855',
                'email' => 'info@sman9-malang.sch.id',
                'website' => 'portal.sman9-mlg.sch.id',
                'logo' => 'school/logo/5Nl25ERAkRM02zx99etQUgwGnMpelCGfJpNmuvm3.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:46:05',
                'updated_at' => '2025-09-09 06:46:05',
            ],
            [
                'id' => 12,
                'name' => 'MAN 3 Jombang',
                'short_name' => 'MANTAB',
                'address' => 'Jl. KH. Abdul Wahab, Tambak Rejo, Kec. Jombang, Kabupaten Jombang, Jawa Timur 61419',
                'phone' => '0321-862352',
                'email' => 'admin@tambakberas.sch.id',
                'website' => 'https://mantambakberas.sch.id/',
                'logo' => 'school/logo/NvTbTOCheDePrjZ8hl0zBtV4Bv8KC5fRQ6ZIGiRW.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:47:00',
                'updated_at' => '2025-09-09 06:47:00',
            ],
            [
                'id' => 13,
                'name' => 'MAN Batu Bara',
                'short_name' => 'MANBARA',
                'address' => 'Jl. Perintis Kemerdekaan No. 76, Lima Puluh Kota, Kec Lima Puluh, Kab, Batubara, Provinsi Sumatera Utara',
                'phone' => '(0622) 96838',
                'email' => 'nfo@manbatubara.sch.id',
                'website' => 'https://manbatubara.sch.id/',
                'logo' => 'school/logo/6uztRkzvkvhPmnFl1c90ZNTdPJvIzqpkmdcm8yun.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:51:45',
                'updated_at' => '2025-09-09 06:51:45',
            ],
            [
                'id' => 14,
                'name' => 'SMA Negeri 8 Pekanbaru',
                'short_name' => 'SMANDEL',
                'address' => 'Jl. Abdul Muis No. 14, Cinta Raja, Pekanbaru',
                'phone' => '853758',
                'email' => 'smandel_pku@yahoo.co.id',
                'website' => 'http://sman8pku.sch.id',
                'logo' => 'school/logo/F9tHtPlD7KkFZiGBVEOGn1F1BM3fiOrhdltNfSck.png',
                'status' => 'active',
                'created_at' => '2025-09-09 06:53:23',
                'updated_at' => '2025-09-09 06:53:23',
            ],
        ];

        foreach ($schools as $row) {
            \App\Models\School::create($row);
        }
    }
}
